name: test
on: workflow_dispatch
jobs:
  build:
    runs-on:
      self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run a line script
        run: |
          echo Hello world!
          sleep 15
          echo Bye!
      
